#ifndef __SYMBOLS_H__
#define __SYMBOLS_H__
#define AND 0
#define ELSEIF 1
#define MOD 2
#define RECORD 3
#define WRITE 4
#define ARRAY 5
#define END 6
#define NOT 7
#define RETURN 8
#define BEGIN 9
#define EXIT 10
#define OF 11
#define THEN 12
#define BY 13
#define FOR 14
#define OR 15
#define TO 16
#define DIV 17
#define IF 18
#define PROCEDURE 19
#define TYPE 20
#define DO 21
#define IS 22
#define PROGRAM 23
#define VAR 24
#define ELSE 25
#define LOOP 26
#define READ 27
#define WHILE 28
#define END_OF_INSTRUCTION 29
#define CONSTANT 30
#define STRING_LITERAL 31
#define DOT 32
#define MULT 33
#define ADD 34
#define SUBSTRACT 35
#define	DIV 36
#define	LESS 37
#define	GREATER 38
#define	ASSIGN 39
#define	LESSEQ 40
#define	GREATEREQ 41
#define	EQUAL 42
#define	DIFF 43
#define	COLON 44
#define	COMMA 45
#define	LPAREN 46
#define	RPAREN 47
#define	LSQBKT 48
#define	RSQBKT 49
#define	LBRKT 50
#define	RBRKT 51
#define	LSQBKTLESS 52
#define GREATERRSQBKT 53
#define IDENTIFIER 54
#define COMMBEG 55
#define COMMEND 56

#endif