#ifndef __SYMBOLS_H__
#define __SYMBOLS_H__
#define AND 0
#define ELSEIF 1
#define MOD 2
#define RECORD 3
#define WRITE 4
#define ARRAY 5
#define END 6
#define NOT 7
#define RETURN 8
#define BEGIN 9
#define EXIT 10
#define OF 11
#define THEN 12
#define BY 13
#define FOR 14
#define OR 15
#define TO 16
#define IF 17
#define PROCEDURE 18
#define TYPE 19
#define DO 20
#define IS 21
#define PROGRAM 22
#define VAR 23
#define ELSE 24
#define LOOP 25
#define READ 26
#define WHILE 27
#define END_OF_INSTRUCTION 28
#define CONSTANT 29
#define STRING_LITERAL 30
#define DOT 31
#define MULT 32
#define ADD 33
#define SUBSTRACT 34
#define	DIV 35
#define	LESS 36
#define	GREATER 37
#define	ASSIGN 38
#define	LESSEQ 39
#define	GREATEREQ 40
#define	EQUAL 41
#define	DIFF 42
#define	COLON 43
#define	COMMA 44
#define	LPAREN 45
#define	RPAREN 46
#define	LSQBKT 47
#define	RSQBKT 48
#define	LBRKT 49
#define	RBRKT 50
#define	LSQBKTLESS 51
#define GREATERRSQBKT 52
#define IDENTIFIER 53
#define COMMBEG 54
#define COMMEND 55
#endif